<?php

namespace Flo\ShunrikBundle\Repository;

/**
 * VoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoiceRepository extends \Doctrine\ORM\EntityRepository
{    
    public function myFind($author){
        $qb = $this->createQueryBuilder('a');

        // On peut ajouter ce qu'on veut avant
        $qb
        ->where('a.author = :author')
        ->setParameter('author', $author)
        ->setMaxResults(5);
      ;
        return $qb
            ->getQuery()
            ->getResult();
    }
}
